export const ROUTES = {
  DASHBOARD: '/',
  PROJECTS: '/projects',
  AGENTS: '/agents',
  AGENT_DETAIL: '/agents/:name',
  // Framework — unified view at /framework/:category
  FRAMEWORK: '/framework',
  FRAMEWORK_RULES: '/framework/rules',
  FRAMEWORK_SKILLS: '/framework/skills',
  FRAMEWORK_KNOWLEDGE: '/framework/knowledge',
  FRAMEWORK_WORKFLOWS: '/framework/workflows',
  FRAMEWORK_TEMPLATES: '/framework/templates',
  FRAMEWORK_SPEC: '/framework/spec',
  // Legacy detail routes (kept for deep linking)
  RULES: '/rules',
  RULE_EDITOR: '/rules/:name',
  SKILLS: '/skills',
  SKILL_DETAIL: '/skills/:name',
  SKILL_EDITOR: '/skills/:name/edit',
  WORKFLOWS: '/workflows',
  WORKFLOW_DETAIL: '/workflows/:name',
  ORCHESTRATOR_DETAIL: '/workflows/:name',
  TEMPLATES: '/templates',
  TEMPLATE_EDITOR: '/templates/:name',
  KNOWLEDGE: '/knowledge',
  KNOWLEDGE_EDITOR: '/knowledge/:path',
  SESSIONS: '/sessions',
  SESSION_DETAIL: '/sessions/:id',
  OBSERVATIONS: '/observations',
  MEMORY: '/memory',
  ANALYTICS: '/analytics',
  EVOLUTION: '/evolution',
  DRAFTS: '/drafts',
  DIAGNOSTICS: '/diagnostics',
  MARKETPLACE: '/marketplace',
  MARKETPLACE_DETAIL: '/marketplace/:type/:slug',
  MCP: '/mcp',
  MCP_HEALTH: '/mcp-health',
  MCP_SERVERS: '/mcp-servers',
  MCP_PLAYGROUND: '/mcp-playground',
  CONFIG: '/config',
  INTEGRATIONS: '/integrations',
  OVERRIDES: '/overrides',
  ADAPTERS: '/adapters',
} as const;

export const POLLING_INTERVALS = {
  MCP_HEALTH: 5000,
  OBSERVATIONS: 10000,
} as const;

export const FILE_WATCHER_DEBOUNCE_MS = 100;
