// ---------------------------------------------------------------------------
// Registry: fetch from remote, fallback to static seed data
// ---------------------------------------------------------------------------

import { MCP_REGISTRY_URL, CONTENT_REGISTRY_URL } from './constants';
import type { McpServerEntry, ContentEntry, RegistryResponse } from './types';

// ── Remote fetch ────────────────────────────────────────────────

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
  if (!res.ok) throw new Error(`Registry fetch failed: ${res.status}`);
  return res.json() as Promise<T>;
}

export async function fetchMcpRegistry(): Promise<{ entries: McpServerEntry[]; remote: boolean }> {
  try {
    const data = await fetchJson<RegistryResponse<McpServerEntry>>(MCP_REGISTRY_URL);
    return { entries: data.entries, remote: true };
  } catch {
    return { entries: FALLBACK_MCP_SERVERS, remote: false };
  }
}

export async function fetchContentRegistry(): Promise<{ entries: ContentEntry[]; remote: boolean }> {
  try {
    const data = await fetchJson<RegistryResponse<ContentEntry>>(CONTENT_REGISTRY_URL);
    return { entries: data.entries, remote: true };
  } catch {
    return { entries: FALLBACK_CONTENT, remote: false };
  }
}

// ── Fallback MCP Servers ────────────────────────────────────────

const FALLBACK_MCP_SERVERS: McpServerEntry[] = [
  {
    type: 'mcp-server',
    slug: 'filesystem',
    name: 'Filesystem',
    description: 'Read, write, and manage files and directories securely',
    author: 'Anthropic',
    authorUrl: 'https://github.com/anthropics',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    category: 'file-system',
    tags: ['filesystem', 'files', 'directories', 'official'],
    transport: ['stdio'],
    features: ['Read files', 'Write files', 'List directories', 'Search files', 'Move/copy files'],
    installCount: 45200,
    trending: false,
    official: true,
    createdAt: '2024-11-25',
    updatedAt: '2026-01-15',
    configSnippet: { mcpServers: { filesystem: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/allowed'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode', 'windsurf'],
  },
  {
    type: 'mcp-server',
    slug: 'github',
    name: 'GitHub',
    description: 'Interact with GitHub repositories, issues, pull requests, and more',
    author: 'GitHub',
    authorUrl: 'https://github.com/github',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
    category: 'devtools',
    tags: ['github', 'git', 'repositories', 'issues', 'pull-requests', 'official'],
    transport: ['stdio'],
    features: ['Repository management', 'Issue tracking', 'Pull request operations', 'Code search', 'Branch management'],
    installCount: 38700,
    trending: true,
    official: true,
    createdAt: '2024-11-25',
    updatedAt: '2026-01-20',
    configSnippet: { mcpServers: { github: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-github'], env: { GITHUB_PERSONAL_ACCESS_TOKEN: '<your-token>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode', 'windsurf'],
  },
  {
    type: 'mcp-server',
    slug: 'brave-search',
    name: 'Brave Search',
    description: 'Web and local search using the Brave Search API',
    author: 'Anthropic',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    category: 'search',
    tags: ['search', 'web', 'brave', 'official'],
    transport: ['stdio'],
    features: ['Web search', 'Local search', 'News search', 'Image search'],
    installCount: 31500,
    trending: false,
    official: true,
    createdAt: '2024-11-25',
    updatedAt: '2026-01-10',
    configSnippet: { mcpServers: { 'brave-search': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-brave-search'], env: { BRAVE_API_KEY: '<your-key>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'puppeteer',
    name: 'Puppeteer',
    description: 'Browser automation for web scraping, screenshots, and testing',
    author: 'Anthropic',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
    category: 'browser',
    tags: ['browser', 'automation', 'scraping', 'screenshots', 'official'],
    transport: ['stdio'],
    features: ['Navigate pages', 'Take screenshots', 'Click elements', 'Fill forms', 'Execute JavaScript'],
    installCount: 28400,
    trending: true,
    official: true,
    createdAt: '2024-11-25',
    updatedAt: '2026-01-18',
    configSnippet: { mcpServers: { puppeteer: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'postgres',
    name: 'PostgreSQL',
    description: 'Read-only access to PostgreSQL databases with schema inspection',
    author: 'Anthropic',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    category: 'database',
    tags: ['database', 'postgresql', 'sql', 'official'],
    transport: ['stdio'],
    features: ['Query execution', 'Schema inspection', 'Table listing', 'Index info'],
    installCount: 22100,
    trending: false,
    official: true,
    createdAt: '2024-11-25',
    updatedAt: '2026-01-12',
    configSnippet: { mcpServers: { postgres: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://localhost/mydb'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'sqlite',
    name: 'SQLite',
    description: 'Read and write SQLite databases with full SQL support',
    author: 'Anthropic',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    category: 'database',
    tags: ['database', 'sqlite', 'sql', 'official'],
    transport: ['stdio'],
    features: ['Query execution', 'Table management', 'Schema inspection', 'Data export'],
    installCount: 19800,
    trending: false,
    official: true,
    createdAt: '2024-11-25',
    updatedAt: '2026-01-12',
    configSnippet: { mcpServers: { sqlite: { command: 'uvx', args: ['mcp-server-sqlite', '--db-path', '/path/to/db.sqlite'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'slack',
    name: 'Slack',
    description: 'Read and send messages, manage channels in Slack workspaces',
    author: 'Anthropic',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    category: 'communication',
    tags: ['slack', 'messaging', 'channels', 'official'],
    transport: ['stdio'],
    features: ['Send messages', 'Read channels', 'List users', 'Search messages'],
    installCount: 15600,
    trending: false,
    official: true,
    createdAt: '2024-12-01',
    updatedAt: '2026-01-10',
    configSnippet: { mcpServers: { slack: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-slack'], env: { SLACK_BOT_TOKEN: '<your-token>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'sequential-thinking',
    name: 'Sequential Thinking',
    description: 'Dynamic, reflective problem-solving through structured thought sequences',
    author: 'Anthropic',
    githubUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
    category: 'ai-llm',
    tags: ['reasoning', 'thinking', 'problem-solving', 'official'],
    transport: ['stdio'],
    features: ['Structured reasoning', 'Thought revision', 'Branch exploration', 'Hypothesis adjustment'],
    installCount: 24300,
    trending: true,
    official: true,
    createdAt: '2025-01-15',
    updatedAt: '2026-01-20',
    configSnippet: { mcpServers: { 'sequential-thinking': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'context7',
    name: 'Context7',
    description: 'Up-to-date documentation and code examples for any library',
    author: 'Upstash',
    authorUrl: 'https://github.com/upstash',
    githubUrl: 'https://github.com/upstash/context7',
    category: 'devtools',
    tags: ['documentation', 'docs', 'libraries', 'code-examples'],
    transport: ['stdio'],
    features: ['Library documentation lookup', 'Code examples', 'Version-aware docs', 'API reference'],
    installCount: 18900,
    trending: true,
    official: false,
    createdAt: '2025-04-01',
    updatedAt: '2026-01-25',
    configSnippet: { mcpServers: { context7: { command: 'npx', args: ['-y', '@upstash/context7-mcp@latest'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode', 'windsurf'],
  },
  {
    type: 'mcp-server',
    slug: 'playwright',
    name: 'Playwright',
    description: 'Browser automation using Playwright for testing and scraping',
    author: 'Microsoft',
    authorUrl: 'https://github.com/microsoft',
    githubUrl: 'https://github.com/microsoft/playwright-mcp',
    category: 'browser',
    tags: ['browser', 'automation', 'testing', 'playwright'],
    transport: ['stdio'],
    features: ['Navigate pages', 'Take screenshots', 'Form interaction', 'Multi-browser support', 'Network interception'],
    installCount: 21300,
    trending: true,
    official: false,
    createdAt: '2025-03-10',
    updatedAt: '2026-01-22',
    configSnippet: { mcpServers: { playwright: { command: 'npx', args: ['-y', '@playwright/mcp@latest'] } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and performance monitoring integration',
    author: 'Sentry',
    authorUrl: 'https://github.com/getsentry',
    githubUrl: 'https://github.com/getsentry/sentry-mcp',
    category: 'monitoring',
    tags: ['errors', 'monitoring', 'performance', 'debugging'],
    transport: ['stdio'],
    features: ['Error retrieval', 'Issue search', 'Performance data', 'Stack trace analysis'],
    installCount: 12400,
    trending: false,
    official: false,
    createdAt: '2025-02-15',
    updatedAt: '2026-01-18',
    configSnippet: { mcpServers: { sentry: { command: 'npx', args: ['-y', '@sentry/mcp-server@latest'], env: { SENTRY_AUTH_TOKEN: '<your-token>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'supabase',
    name: 'Supabase',
    description: 'Manage Supabase projects, databases, and edge functions',
    author: 'Supabase',
    authorUrl: 'https://github.com/supabase',
    githubUrl: 'https://github.com/supabase-community/supabase-mcp',
    category: 'database',
    tags: ['supabase', 'database', 'auth', 'storage', 'edge-functions'],
    transport: ['stdio'],
    features: ['Database queries', 'Schema management', 'Auth operations', 'Storage management', 'Edge function deployment'],
    installCount: 16700,
    trending: true,
    official: false,
    createdAt: '2025-02-20',
    updatedAt: '2026-01-28',
    configSnippet: { mcpServers: { supabase: { command: 'npx', args: ['-y', 'supabase-mcp-server@latest'], env: { SUPABASE_URL: '<url>', SUPABASE_SERVICE_ROLE_KEY: '<key>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage Cloudflare Workers, KV, R2, and D1 resources',
    author: 'Cloudflare',
    authorUrl: 'https://github.com/cloudflare',
    githubUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    category: 'cloud',
    tags: ['cloudflare', 'workers', 'kv', 'r2', 'd1', 'edge'],
    transport: ['stdio'],
    features: ['Workers management', 'KV store operations', 'R2 storage', 'D1 database', 'DNS management'],
    installCount: 11200,
    trending: false,
    official: false,
    createdAt: '2025-01-20',
    updatedAt: '2026-01-15',
    configSnippet: { mcpServers: { cloudflare: { command: 'npx', args: ['-y', '@cloudflare/mcp-server-cloudflare'], env: { CLOUDFLARE_API_TOKEN: '<your-token>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'linear',
    name: 'Linear',
    description: 'Issue tracking and project management with Linear',
    author: 'Linear',
    authorUrl: 'https://github.com/linear',
    githubUrl: 'https://github.com/linear/linear-mcp-server',
    category: 'devtools',
    tags: ['linear', 'issues', 'project-management', 'agile'],
    transport: ['stdio'],
    features: ['Create issues', 'Search issues', 'Update status', 'List projects', 'Team management'],
    installCount: 9800,
    trending: false,
    official: false,
    createdAt: '2025-03-05',
    updatedAt: '2026-01-20',
    configSnippet: { mcpServers: { linear: { command: 'npx', args: ['-y', '@linear/mcp-server'], env: { LINEAR_API_KEY: '<your-key>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'exa-search',
    name: 'Exa Search',
    description: 'AI-powered web search with content extraction',
    author: 'Exa',
    authorUrl: 'https://github.com/exa-labs',
    githubUrl: 'https://github.com/exa-labs/exa-mcp-server',
    category: 'search',
    tags: ['search', 'web', 'ai', 'content-extraction'],
    transport: ['stdio'],
    features: ['Semantic search', 'Content extraction', 'Similar page finding', 'Keyword search'],
    installCount: 14200,
    trending: false,
    official: false,
    createdAt: '2025-01-10',
    updatedAt: '2026-01-15',
    configSnippet: { mcpServers: { exa: { command: 'npx', args: ['-y', 'exa-mcp-server'], env: { EXA_API_KEY: '<your-key>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'tavily',
    name: 'Tavily Search',
    description: 'AI-optimized search API designed for LLM applications',
    author: 'Tavily',
    authorUrl: 'https://github.com/tavily-ai',
    githubUrl: 'https://github.com/tavily-ai/tavily-mcp',
    category: 'search',
    tags: ['search', 'web', 'ai', 'research'],
    transport: ['stdio'],
    features: ['Web search', 'Content extraction', 'Research mode', 'Domain filtering'],
    installCount: 13100,
    trending: false,
    official: false,
    createdAt: '2025-02-01',
    updatedAt: '2026-01-18',
    configSnippet: { mcpServers: { tavily: { command: 'npx', args: ['-y', 'tavily-mcp@latest'], env: { TAVILY_API_KEY: '<your-key>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'neon',
    name: 'Neon',
    description: 'Serverless Postgres management with branching and autoscaling',
    author: 'Neon',
    authorUrl: 'https://github.com/neondatabase',
    githubUrl: 'https://github.com/neondatabase/mcp-server-neon',
    category: 'database',
    tags: ['neon', 'postgres', 'serverless', 'database', 'branching'],
    transport: ['stdio'],
    features: ['Database branching', 'Query execution', 'Schema management', 'Autoscaling control'],
    installCount: 8900,
    trending: false,
    official: false,
    createdAt: '2025-03-01',
    updatedAt: '2026-01-20',
    configSnippet: { mcpServers: { neon: { command: 'npx', args: ['-y', '@neondatabase/mcp-server-neon'], env: { NEON_API_KEY: '<your-key>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
  {
    type: 'mcp-server',
    slug: 'vercel',
    name: 'Vercel',
    description: 'Manage Vercel deployments, projects, and environment variables',
    author: 'Vercel',
    authorUrl: 'https://github.com/vercel',
    githubUrl: 'https://github.com/vercel/mcp-server-vercel',
    category: 'cloud',
    tags: ['vercel', 'deployment', 'hosting', 'edge'],
    transport: ['stdio'],
    features: ['Deploy management', 'Project config', 'Environment variables', 'Domain management', 'Log streaming'],
    installCount: 10500,
    trending: false,
    official: false,
    createdAt: '2025-02-10',
    updatedAt: '2026-01-22',
    configSnippet: { mcpServers: { vercel: { command: 'npx', args: ['-y', '@vercel/mcp-server-vercel'], env: { VERCEL_TOKEN: '<your-token>' } } } },
    compatibility: ['claude-code', 'cursor', 'vscode'],
  },
];

// ── Fallback Content ────────────────────────────────────────────

const FALLBACK_CONTENT: ContentEntry[] = [
  // ── Agents (9) ──────────────────────────────────────────────
  {
    type: 'content',
    slug: 'master-orchestrator',
    name: 'Master Orchestrator',
    description: 'Strategic mapping & delegation — decomposes user intent, queries TKB, maps execution paths',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['orchestration', 'delegation', 'routing', 'strategy', 'core'],
    installCount: 4200,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Master Orchestrator\n\nStrategic mapping and delegation. Decomposes user intent, queries Technology Knowledge Base, and maps optimal execution paths.',
    installCommand: 'npx @aidd.md/cli install agent master-orchestrator',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'knowledge-architect-agent',
    name: 'Knowledge Architect',
    description: 'TKB curator & schema enforcer — maintains Technology Knowledge Base, validates schema compliance',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['knowledge-base', 'schema', 'curation', 'validation'],
    installCount: 2100,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Knowledge Architect Agent\n\nMaintains the Technology Knowledge Base, validates schema compliance, and updates benchmarks.',
    installCommand: 'npx @aidd.md/cli install agent knowledge-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'system-architect-agent',
    name: 'System Architect',
    description: 'Complete system design — architecture analysis, technical debt assessment, ADRs',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['architecture', 'system-design', 'adr', 'technical-debt'],
    installCount: 3500,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# System Architect Agent\n\nComplete system design, architecture analysis, and technical debt assessment.',
    installCommand: 'npx @aidd.md/cli install agent system-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'fullstack-agent',
    name: 'Fullstack Agent',
    description: 'End-to-end implementation — complete features, integrations, full-stack development',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['fullstack', 'implementation', 'integration', 'features'],
    installCount: 3800,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Fullstack Agent\n\nEnd-to-end implementation for complete features, integrations, and full-stack development.',
    installCommand: 'npx @aidd.md/cli install agent fullstack',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'interface-artisan-agent',
    name: 'Interface Artisan',
    description: 'UI/UX components — WCAG accessibility, pixel-perfect implementation, design systems',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['ui', 'ux', 'accessibility', 'wcag', 'components'],
    installCount: 2800,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Interface Artisan Agent\n\nUI/UX component development with WCAG accessibility and pixel-perfect implementation.',
    installCommand: 'npx @aidd.md/cli install agent interface-artisan',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'quality-engineer-agent',
    name: 'Quality Engineer',
    description: 'Test generation — coverage analysis, edge cases, TDD workflows',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['testing', 'tdd', 'coverage', 'quality', 'edge-cases'],
    installCount: 2200,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Quality Engineer Agent\n\nTest generation, coverage analysis, edge case discovery, and TDD workflows.',
    installCommand: 'npx @aidd.md/cli install agent quality-engineer',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'security-architect-agent',
    name: 'Security Architect',
    description: 'Security audits — vulnerability analysis, IAM, threat modeling, OWASP compliance',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['security', 'audit', 'owasp', 'iam', 'threat-modeling'],
    installCount: 1900,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Security Architect Agent\n\nSecurity audits, vulnerability analysis, IAM patterns, and threat modeling.',
    installCommand: 'npx @aidd.md/cli install agent security-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'platform-engineer-agent',
    name: 'Platform Engineer',
    description: 'CI/CD, infrastructure, deployment pipelines, monitoring, containerization',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['cicd', 'infrastructure', 'deployment', 'monitoring', 'devops'],
    installCount: 1700,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Platform Engineer Agent\n\nCI/CD pipelines, infrastructure management, deployment, and monitoring.',
    installCommand: 'npx @aidd.md/cli install agent platform-engineer',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'i18n-specialist-agent',
    name: 'i18n Specialist',
    description: 'Internationalization — translation workflows, locale management, RTL support',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/blob/main/AGENTS.md',
    contentType: 'agent',
    tags: ['i18n', 'localization', 'translations', 'rtl', 'next-intl'],
    installCount: 1300,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# i18n Specialist Agent\n\nInternationalization patterns, translation workflows, and locale management.',
    installCommand: 'npx @aidd.md/cli install agent i18n-specialist',
    compatibility: ['claude-code', 'cursor'],
  },

  // ── Skills (11) ──────────────────────────────────────────────
  {
    type: 'content',
    slug: 'system-architect',
    name: 'System Architect',
    description: 'Design scalable system architectures — microservices, monoliths, event-driven patterns',
    author: 'aidd.md',
    authorUrl: 'https://github.com/DerianAndre/aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/system-architect',
    contentType: 'skill',
    tags: ['architecture', 'system-design', 'microservices', 'scalability', 'core'],
    installCount: 3400,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# System Architect\n\nDesign scalable system architectures with trade-off analysis, ADRs, and infrastructure planning.',
    installCommand: 'npx @aidd.md/cli install skill system-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'contract-architect',
    name: 'Contract Architect',
    description: 'Design APIs, contracts, and integration boundaries — REST, GraphQL, gRPC, tRPC',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/contract-architect',
    contentType: 'skill',
    tags: ['api', 'contracts', 'rest', 'graphql', 'grpc', 'trpc'],
    installCount: 2600,
    trending: false,
    official: true,
    createdAt: '2025-06-15',
    updatedAt: '2026-01-28',
    markdownContent: '# Contract Architect\n\nDesign type-safe API contracts, schema validation, and integration boundaries.',
    installCommand: 'npx @aidd.md/cli install skill contract-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'interface-artisan',
    name: 'Interface Artisan',
    description: 'Craft pixel-perfect UI components — React, accessibility, design systems',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/interface-artisan',
    contentType: 'skill',
    tags: ['frontend', 'ui', 'components', 'react', 'accessibility'],
    installCount: 2900,
    trending: true,
    official: true,
    createdAt: '2025-06-15',
    updatedAt: '2026-01-28',
    markdownContent: '# Interface Artisan\n\nBuild accessible, reusable UI components with design system consistency.',
    installCommand: 'npx @aidd.md/cli install skill interface-artisan',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'design-architect',
    name: 'Design Architect',
    description: 'UX/UI design intelligence — layouts, color systems, typography, motion design',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/design-architect',
    contentType: 'skill',
    tags: ['design', 'ux', 'ui', 'typography', 'color-systems', 'motion'],
    installCount: 2400,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-25',
    markdownContent: '# Design Architect\n\nDesign systems, color palettes, typography scales, layout composition, and motion design.',
    installCommand: 'npx @aidd.md/cli install skill design-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'experience-engineer',
    name: 'Experience Engineer',
    description: 'Performance optimization — Core Web Vitals, bundle size, rendering, caching',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/experience-engineer',
    contentType: 'skill',
    tags: ['performance', 'optimization', 'web-vitals', 'caching', 'rendering'],
    installCount: 2200,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Experience Engineer\n\nOptimize frontend performance — Core Web Vitals, bundle splitting, lazy loading, caching strategies.',
    installCommand: 'npx @aidd.md/cli install skill experience-engineer',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'data-architect',
    name: 'Data Architect',
    description: 'Database design — schemas, migrations, indexing, query optimization, ORMs',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/data-architect',
    contentType: 'skill',
    tags: ['database', 'schema', 'migrations', 'orm', 'sql', 'indexing'],
    installCount: 2100,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-01-22',
    markdownContent: '# Data Architect\n\nDesign database schemas, write migrations, optimize queries, and configure ORMs.',
    installCommand: 'npx @aidd.md/cli install skill data-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'quality-engineer',
    name: 'Quality Engineer',
    description: 'Testing strategies — unit, integration, e2e, mocking, coverage, TDD',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/quality-engineer',
    contentType: 'skill',
    tags: ['testing', 'tdd', 'unit-tests', 'e2e', 'coverage', 'mocking'],
    installCount: 2000,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-18',
    markdownContent: '# Quality Engineer\n\nTest strategies, TDD workflows, mocking patterns, and coverage optimization.',
    installCommand: 'npx @aidd.md/cli install skill quality-engineer',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'security-architect',
    name: 'Security Architect',
    description: 'Security auditing — OWASP, threat modeling, auth patterns, vulnerability scanning',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/security-architect',
    contentType: 'skill',
    tags: ['security', 'owasp', 'auth', 'threat-modeling', 'vulnerabilities'],
    installCount: 1800,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Security Architect\n\nThreat modeling, OWASP compliance, auth patterns, and vulnerability analysis.',
    installCommand: 'npx @aidd.md/cli install skill security-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'platform-engineer',
    name: 'Platform Engineer',
    description: 'CI/CD, infrastructure, Docker, Kubernetes, deployment pipelines',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/platform-engineer',
    contentType: 'skill',
    tags: ['cicd', 'docker', 'kubernetes', 'infrastructure', 'devops'],
    installCount: 1700,
    trending: false,
    official: true,
    createdAt: '2025-08-15',
    updatedAt: '2026-01-18',
    markdownContent: '# Platform Engineer\n\nCI/CD pipelines, containerization, orchestration, and infrastructure as code.',
    installCommand: 'npx @aidd.md/cli install skill platform-engineer',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'knowledge-architect',
    name: 'Knowledge Architect',
    description: 'Documentation, knowledge bases, ADRs, technical writing',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/knowledge-architect',
    contentType: 'skill',
    tags: ['documentation', 'knowledge-base', 'adr', 'technical-writing'],
    installCount: 1500,
    trending: false,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-01-15',
    markdownContent: '# Knowledge Architect\n\nStructured documentation, ADRs, knowledge base management, and technical writing.',
    installCommand: 'npx @aidd.md/cli install skill knowledge-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'i18n-specialist',
    name: 'i18n Specialist',
    description: 'Internationalization — translation workflows, locale management, RTL support',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/i18n-specialist',
    contentType: 'skill',
    tags: ['i18n', 'localization', 'translations', 'rtl', 'locale'],
    installCount: 1300,
    trending: false,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-01-12',
    markdownContent: '# i18n Specialist\n\nInternationalization workflows, translation management, locale configuration, and RTL support.',
    installCommand: 'npx @aidd.md/cli install skill i18n-specialist',
    compatibility: ['claude-code', 'cursor'],
  },

  // ── Workflows (9) ────────────────────────────────────────────
  {
    type: 'content',
    slug: 'analyze-workflow',
    name: 'Analyze Workflow',
    description: 'Deep codebase analysis — trace execution paths, map architecture, understand patterns',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/analyze.md',
    contentType: 'workflow',
    tags: ['analysis', 'codebase', 'architecture', 'exploration'],
    installCount: 1500,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-10',
    markdownContent: '# Analyze Workflow\n\nSystematic codebase exploration and architecture mapping.',
    installCommand: 'npx @aidd.md/cli install workflow analyze',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'review-workflow',
    name: 'Review Workflow',
    description: 'Code review with confidence-based filtering and actionable feedback',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/review.md',
    contentType: 'workflow',
    tags: ['code-review', 'quality', 'feedback', 'pr-review'],
    installCount: 1800,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-12',
    markdownContent: '# Review Workflow\n\nStructured code review with evidence-based feedback.',
    installCommand: 'npx @aidd.md/cli install workflow review',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'design-workflow',
    name: 'Design Workflow',
    description: 'End-to-end design process — research, wireframes, prototyping, handoff',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/design.md',
    contentType: 'workflow',
    tags: ['design', 'wireframes', 'prototyping', 'ux-research'],
    installCount: 1200,
    trending: false,
    official: true,
    createdAt: '2025-06-15',
    updatedAt: '2026-01-15',
    markdownContent: '# Design Workflow\n\nStructured design process from research through prototyping to developer handoff.',
    installCommand: 'npx @aidd.md/cli install workflow design',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'audit-workflow',
    name: 'Audit Workflow',
    description: 'Security and quality auditing — vulnerability scanning, compliance checks',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/audit.md',
    contentType: 'workflow',
    tags: ['audit', 'security', 'compliance', 'vulnerability-scanning'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-18',
    markdownContent: '# Audit Workflow\n\nSystematic security and quality auditing with actionable remediation steps.',
    installCommand: 'npx @aidd.md/cli install workflow audit',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'test-workflow',
    name: 'Test Workflow',
    description: 'Testing pipeline — strategy selection, test writing, coverage analysis, CI integration',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/test.md',
    contentType: 'workflow',
    tags: ['testing', 'coverage', 'ci', 'test-strategy'],
    installCount: 1400,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-15',
    markdownContent: '# Test Workflow\n\nEnd-to-end testing pipeline from strategy through execution to coverage reporting.',
    installCommand: 'npx @aidd.md/cli install workflow test',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'feature-branch-workflow',
    name: 'Feature Branch Workflow',
    description: 'Git branching strategy — feature branches, PR workflow, merge strategies',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/feature-branch.md',
    contentType: 'workflow',
    tags: ['git', 'branching', 'pull-requests', 'merge-strategy'],
    installCount: 1600,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-01-20',
    markdownContent: '# Feature Branch Workflow\n\nGit branching strategies, PR workflows, and merge conflict resolution.',
    installCommand: 'npx @aidd.md/cli install workflow feature-branch',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'docs-workflow',
    name: 'Documentation Workflow',
    description: 'Documentation generation — API docs, guides, changelogs, README templates',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/docs.md',
    contentType: 'workflow',
    tags: ['documentation', 'api-docs', 'changelog', 'readme'],
    installCount: 900,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-10',
    markdownContent: '# Documentation Workflow\n\nGenerate and maintain API docs, guides, changelogs, and README files.',
    installCommand: 'npx @aidd.md/cli install workflow docs',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'product-workflow',
    name: 'Product Workflow',
    description: 'Product development — user stories, acceptance criteria, sprint planning',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/product.md',
    contentType: 'workflow',
    tags: ['product', 'user-stories', 'acceptance-criteria', 'sprint-planning'],
    installCount: 800,
    trending: false,
    official: true,
    createdAt: '2025-08-15',
    updatedAt: '2026-01-12',
    markdownContent: '# Product Workflow\n\nProduct development lifecycle from user stories to sprint planning.',
    installCommand: 'npx @aidd.md/cli install workflow product',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'technology-selection-workflow',
    name: 'Technology Selection Workflow',
    description: 'Structured technology evaluation — comparison matrices, proof of concepts, decision records',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/technology-selection.md',
    contentType: 'workflow',
    tags: ['technology', 'evaluation', 'comparison', 'adr', 'decision-making'],
    installCount: 700,
    trending: false,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-01-15',
    markdownContent: '# Technology Selection Workflow\n\nStructured evaluation framework for choosing technologies with ADRs.',
    installCommand: 'npx @aidd.md/cli install workflow technology-selection',
    compatibility: ['claude-code'],
  },

  // ── Rules (10) ───────────────────────────────────────────────
  {
    type: 'content',
    slug: 'global-rules',
    name: 'Global Rules',
    description: 'Framework-wide immutable constraints — code style, naming, security, testing',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/global.md',
    contentType: 'rule',
    tags: ['rules', 'conventions', 'code-style', 'global'],
    installCount: 3200,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Global Rules\n\nImmutable framework constraints applied to all agents and tasks.',
    installCommand: 'npx @aidd.md/cli install rule global',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'orchestrator-rules',
    name: 'Orchestrator Rules',
    description: 'Orchestration constraints — agent selection, task routing, coordination protocols',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/orchestrator.md',
    contentType: 'rule',
    tags: ['rules', 'orchestration', 'routing', 'coordination'],
    installCount: 2200,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-28',
    markdownContent: '# Orchestrator Rules\n\nConstraints for agent selection, task classification, and multi-agent coordination.',
    installCommand: 'npx @aidd.md/cli install rule orchestrator',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'frontend-rules',
    name: 'Frontend Rules',
    description: 'Frontend constraints — React patterns, CSS conventions, accessibility requirements',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/frontend.md',
    contentType: 'rule',
    tags: ['rules', 'frontend', 'react', 'css', 'accessibility'],
    installCount: 1900,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-28',
    markdownContent: '# Frontend Rules\n\nReact patterns, CSS conventions, component architecture, and accessibility requirements.',
    installCommand: 'npx @aidd.md/cli install rule frontend',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'backend-rules',
    name: 'Backend Rules',
    description: 'Backend constraints — API design, error handling, validation, database access patterns',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/backend.md',
    contentType: 'rule',
    tags: ['rules', 'backend', 'api', 'error-handling', 'validation'],
    installCount: 1800,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-25',
    markdownContent: '# Backend Rules\n\nAPI design patterns, error handling, validation, and database access conventions.',
    installCommand: 'npx @aidd.md/cli install rule backend',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'security-rules',
    name: 'Security Rules',
    description: 'Security constraints — input validation, auth patterns, OWASP compliance',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/security.md',
    contentType: 'rule',
    tags: ['rules', 'security', 'owasp', 'auth', 'input-validation'],
    installCount: 1600,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-01-22',
    markdownContent: '# Security Rules\n\nSecurity-first constraints covering OWASP, authentication, and input validation.',
    installCommand: 'npx @aidd.md/cli install rule security',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'testing-rules',
    name: 'Testing Rules',
    description: 'Testing constraints — coverage thresholds, naming conventions, test organization',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/testing.md',
    contentType: 'rule',
    tags: ['rules', 'testing', 'coverage', 'naming', 'organization'],
    installCount: 1400,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-18',
    markdownContent: '# Testing Rules\n\nTest coverage thresholds, naming conventions, and test file organization.',
    installCommand: 'npx @aidd.md/cli install rule testing',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'interfaces-rules',
    name: 'Interfaces Rules',
    description: 'UI/UX constraints — responsive design, color systems, typography, spacing',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/interfaces.md',
    contentType: 'rule',
    tags: ['rules', 'ui', 'ux', 'responsive', 'design-system'],
    installCount: 1300,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Interfaces Rules\n\nUI/UX design constraints for responsive layouts, color systems, and typography.',
    installCommand: 'npx @aidd.md/cli install rule interfaces',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'code-style-rules',
    name: 'Code Style Rules',
    description: 'Code style constraints — naming, formatting, imports, file organization',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/code-style.md',
    contentType: 'rule',
    tags: ['rules', 'code-style', 'naming', 'formatting', 'imports'],
    installCount: 2000,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-25',
    markdownContent: '# Code Style Rules\n\nNaming conventions, import ordering, file organization, and formatting standards.',
    installCommand: 'npx @aidd.md/cli install rule code-style',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'git-workflow-rules',
    name: 'Git Workflow Rules',
    description: 'Git constraints — commit messages, branching, PR conventions, merge strategies',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/git-workflow.md',
    contentType: 'rule',
    tags: ['rules', 'git', 'commits', 'branching', 'pull-requests'],
    installCount: 1500,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Git Workflow Rules\n\nCommit message format, branching strategy, PR conventions, and merge protocols.',
    installCommand: 'npx @aidd.md/cli install rule git-workflow',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'documentation-rules',
    name: 'Documentation Rules',
    description: 'Documentation constraints — structure, formatting, ADR templates, changelog standards',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/documentation.md',
    contentType: 'rule',
    tags: ['rules', 'documentation', 'adr', 'changelog', 'formatting'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-15',
    markdownContent: '# Documentation Rules\n\nDocumentation structure, formatting standards, and ADR templates.',
    installCommand: 'npx @aidd.md/cli install rule documentation',
    compatibility: ['claude-code', 'cursor'],
  },
  // ── Templates (3 active + 9 absorbed) ──────────────────────
  {
    type: 'content',
    slug: 'routing-template',
    name: 'Routing Template',
    description: 'Task-to-template mapping with PAUS skill equivalents and fallback chains',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/templates/routing.md',
    contentType: 'template',
    tags: ['routing', 'task-classification', 'templates', 'paus'],
    installCount: 1500,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Routing Template\n\nMaps task types to appropriate templates and PAUS skill equivalents.',
    installCommand: 'npx @aidd.md/cli install template routing',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'brainstorming-template',
    name: 'Brainstorming Template',
    description: 'Structured ideation — divergent thinking, convergence, evaluation, selection',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/templates/brainstorming.md',
    contentType: 'template',
    tags: ['brainstorming', 'ideation', 'planning'],
    installCount: 1200,
    trending: false,
    official: true,
    createdAt: '2025-06-15',
    updatedAt: '2026-01-18',
    markdownContent: '# Brainstorming Template\n\nStructured ideation with divergent thinking, convergence, and solution evaluation.',
    installCommand: 'npx @aidd.md/cli install template brainstorming',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'analysis-template',
    name: 'Analysis Template',
    description: 'Systematic analysis — absorbed into orchestrator rules (root cause, impact assessment, recommendation matrix)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/orchestrator.md',
    contentType: 'rule',
    tags: ['analysis', 'root-cause', 'impact-assessment', 'orchestrator'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-06-15',
    updatedAt: '2026-02-06',
    markdownContent: '# Analysis (Orchestrator Rules)\n\nSystematic analysis with root cause identification and recommendation matrices. Absorbed into orchestrator rules.',
    installCommand: 'npx @aidd.md/cli install rule orchestrator',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'frontend-template',
    name: 'Frontend Template',
    description: 'Frontend implementation — absorbed into frontend rules (component architecture, state management, styling)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/frontend.md',
    contentType: 'rule',
    tags: ['frontend', 'components', 'state-management', 'styling', 'rules'],
    installCount: 1300,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-02-06',
    markdownContent: '# Frontend (Frontend Rules)\n\nComponent architecture, state management patterns, and styling conventions. Absorbed into frontend rules.',
    installCommand: 'npx @aidd.md/cli install rule frontend',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'backend-template',
    name: 'Backend Template',
    description: 'Backend implementation — absorbed into backend rules (API design, service layer, data access, error handling)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/backend.md',
    contentType: 'rule',
    tags: ['backend', 'api', 'services', 'data-access', 'rules'],
    installCount: 1200,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-02-06',
    markdownContent: '# Backend (Backend Rules)\n\nAPI design, service architecture, data access patterns, and error handling. Absorbed into backend rules.',
    installCommand: 'npx @aidd.md/cli install rule backend',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'database-template',
    name: 'Database Template',
    description: 'Database design — absorbed into backend rules (schema modeling, migrations, indexing strategies)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/backend.md',
    contentType: 'rule',
    tags: ['database', 'schema', 'migrations', 'indexing', 'backend', 'rules'],
    installCount: 900,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-02-06',
    markdownContent: '# Database (Backend Rules)\n\nSchema modeling, migration strategies, and indexing best practices. Absorbed into backend rules.',
    installCommand: 'npx @aidd.md/cli install rule backend',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'testing-template',
    name: 'Testing Template',
    description: 'Test implementation — absorbed into testing rules (test strategies, fixtures, mocking, assertions)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/testing.md',
    contentType: 'rule',
    tags: ['testing', 'fixtures', 'mocking', 'assertions', 'rules'],
    installCount: 1000,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-02-06',
    markdownContent: '# Testing (Testing Rules)\n\nTest strategies, fixture patterns, mocking approaches, and assertion best practices. Absorbed into testing rules.',
    installCommand: 'npx @aidd.md/cli install rule testing',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'security-audit-template',
    name: 'Security Audit Template',
    description: 'Security audit — absorbed into analyze workflow (OWASP checklist, vulnerability classification, remediation plan)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/analyze.md',
    contentType: 'workflow',
    tags: ['security', 'audit', 'owasp', 'vulnerabilities', 'workflow'],
    installCount: 800,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-02-06',
    markdownContent: '# Security Audit (Analyze Workflow)\n\nOWASP-based security audit with vulnerability classification and remediation. Absorbed into analyze workflow.',
    installCommand: 'npx @aidd.md/cli install workflow analyze',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'api-design-template',
    name: 'API Design Template',
    description: 'API design — absorbed into contract-architect skill (REST/GraphQL conventions, versioning, pagination, error formats)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/skills/contract-architect/SKILL.md',
    contentType: 'skill',
    tags: ['api', 'rest', 'graphql', 'versioning', 'pagination', 'contract-architect'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-02-06',
    markdownContent: '# API Design (Contract Architect Skill)\n\nREST/GraphQL conventions, versioning strategies, and error format standards. Absorbed into contract-architect skill.',
    installCommand: 'npx @aidd.md/cli install skill contract-architect',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'code-review-template',
    name: 'Code Review Template',
    description: 'Code review — absorbed into review workflow (checklist, severity levels, feedback conventions)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/workflows/review.md',
    contentType: 'workflow',
    tags: ['code-review', 'checklist', 'feedback', 'quality', 'workflow'],
    installCount: 1000,
    trending: false,
    official: true,
    createdAt: '2025-08-15',
    updatedAt: '2026-02-06',
    markdownContent: '# Code Review (Review Workflow)\n\nStructured code review with severity levels and actionable feedback. Absorbed into review workflow.',
    installCommand: 'npx @aidd.md/cli install workflow review',
    compatibility: ['claude-code'],
  },
  {
    type: 'content',
    slug: 'performance-template',
    name: 'Performance Template',
    description: 'Performance optimization — absorbed into performance rules (profiling, bottleneck analysis, optimization strategies)',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/rules/performance.md',
    contentType: 'rule',
    tags: ['performance', 'profiling', 'optimization', 'bottlenecks', 'rules'],
    installCount: 850,
    trending: false,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-02-06',
    markdownContent: '# Performance (Performance Rules)\n\nProfiling workflows, bottleneck analysis, and optimization strategies. Absorbed into performance rules.',
    installCommand: 'npx @aidd.md/cli install rule performance',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'migration-template',
    name: 'Migration Template',
    description: 'Migration planning — dependency updates, breaking changes, rollback strategies',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/templates/migration.md',
    contentType: 'template',
    tags: ['migration', 'upgrades', 'breaking-changes', 'rollback'],
    installCount: 750,
    trending: false,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-01-12',
    markdownContent: '# Migration Template\n\nMigration planning with dependency analysis, breaking change tracking, and rollback strategies.',
    installCommand: 'npx @aidd.md/cli install template migration',
    compatibility: ['claude-code'],
  },

  // ── Knowledge (20 representative entries) ────────────────────
  {
    type: 'content',
    slug: 'react-tkb',
    name: 'React Knowledge',
    description: 'React 19 — Server Components, hooks, concurrent features, performance patterns',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/patterns/react-server-components.md',
    contentType: 'knowledge',
    tags: ['react', 'hooks', 'server-components', 'concurrent'],
    installCount: 2100,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-25',
    markdownContent: '# React 19 Knowledge\n\nPatterns, hooks, server components, and performance optimization for React 19.',
    installCommand: 'npx @aidd.md/cli install knowledge react',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'tailwind-tkb',
    name: 'Tailwind CSS Knowledge',
    description: 'Tailwind CSS 4 — CSS-only config, OKLCH colors, modern variants, @theme',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/css/tailwind.md',
    contentType: 'knowledge',
    tags: ['tailwind', 'css', 'styling', 'oklch'],
    installCount: 1800,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Tailwind CSS 4 Knowledge\n\nCSS-only configuration, OKLCH colors, modern variants, and TW4 patterns.',
    installCommand: 'npx @aidd.md/cli install knowledge tailwind',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'nextjs-tkb',
    name: 'Next.js Knowledge',
    description: 'Next.js 15 — App Router, Server Actions, streaming, caching, middleware',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/meta-frameworks/nextjs.md',
    contentType: 'knowledge',
    tags: ['nextjs', 'app-router', 'server-actions', 'streaming'],
    installCount: 1900,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-28',
    markdownContent: '# Next.js 15 Knowledge\n\nApp Router patterns, Server Actions, streaming SSR, and caching strategies.',
    installCommand: 'npx @aidd.md/cli install knowledge nextjs',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'astro-tkb',
    name: 'Astro Knowledge',
    description: 'Astro 5 — Content Layer, Actions, Islands, ClientRouter, View Transitions',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/meta-frameworks/astro.md',
    contentType: 'knowledge',
    tags: ['astro', 'islands', 'content-layer', 'static-sites'],
    installCount: 1400,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-22',
    markdownContent: '# Astro 5 Knowledge\n\nContent Layer API, Actions, Islands architecture, and View Transitions.',
    installCommand: 'npx @aidd.md/cli install knowledge astro',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'nestjs-tkb',
    name: 'NestJS Knowledge',
    description: 'NestJS 11 — Modules, Controllers, Services, Guards, Pipes, Interceptors',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/backend/frameworks/nestjs.md',
    contentType: 'knowledge',
    tags: ['nestjs', 'modules', 'controllers', 'services', 'backend'],
    installCount: 1600,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-25',
    markdownContent: '# NestJS 11 Knowledge\n\nModule architecture, dependency injection, guards, pipes, and interceptors.',
    installCommand: 'npx @aidd.md/cli install knowledge nestjs',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'prisma-tkb',
    name: 'Prisma Knowledge',
    description: 'Prisma 7 — Schema modeling, type-safe queries, migrations, relations',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/data/orms/prisma.md',
    contentType: 'knowledge',
    tags: ['prisma', 'orm', 'database', 'schema', 'migrations'],
    installCount: 1500,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-01-22',
    markdownContent: '# Prisma 7 Knowledge\n\nSchema modeling, type-safe queries, migration workflows, and relation patterns.',
    installCommand: 'npx @aidd.md/cli install knowledge prisma',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'drizzle-tkb',
    name: 'Drizzle Knowledge',
    description: 'Drizzle ORM — SQL-first, type-safe queries, schema, migrations, joins',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/data/orms/drizzle.md',
    contentType: 'knowledge',
    tags: ['drizzle', 'orm', 'sql', 'database', 'type-safe'],
    installCount: 1300,
    trending: true,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-25',
    markdownContent: '# Drizzle ORM Knowledge\n\nSQL-first ORM with type-safe queries, schema definitions, and migration tooling.',
    installCommand: 'npx @aidd.md/cli install knowledge drizzle',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'vitest-tkb',
    name: 'Vitest Knowledge',
    description: 'Vitest 4 — Vite-native testing, snapshots, coverage, mocking, workspaces',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/testing/unit/vitest.md',
    contentType: 'knowledge',
    tags: ['vitest', 'testing', 'unit-tests', 'coverage', 'mocking'],
    installCount: 1200,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Vitest 4 Knowledge\n\nVite-native test runner with snapshots, coverage, mocking, and workspace support.',
    installCommand: 'npx @aidd.md/cli install knowledge vitest',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'playwright-tkb',
    name: 'Playwright Knowledge',
    description: 'Playwright — E2E testing, cross-browser, auto-wait, visual regression',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/testing/e2e/playwright.md',
    contentType: 'knowledge',
    tags: ['playwright', 'e2e', 'testing', 'cross-browser', 'visual-regression'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-18',
    markdownContent: '# Playwright Knowledge\n\nEnd-to-end testing with auto-wait, cross-browser support, and visual regression.',
    installCommand: 'npx @aidd.md/cli install knowledge playwright',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'zustand-tkb',
    name: 'Zustand Knowledge',
    description: 'Zustand 5 — Minimal state management, selectors, middleware, devtools',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/patterns/zustand.md',
    contentType: 'knowledge',
    tags: ['zustand', 'state-management', 'react', 'selectors'],
    installCount: 1400,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-22',
    markdownContent: '# Zustand 5 Knowledge\n\nMinimal state management with selectors, middleware, and devtools integration.',
    installCommand: 'npx @aidd.md/cli install knowledge zustand',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'tauri-tkb',
    name: 'Tauri Knowledge',
    description: 'Tauri 2 — Rust backend, IPC, permissions, plugins, cross-platform desktop/mobile',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/infrastructure/desktop/tauri.md',
    contentType: 'knowledge',
    tags: ['tauri', 'desktop', 'rust', 'ipc', 'cross-platform'],
    installCount: 1000,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Tauri 2 Knowledge\n\nRust backend, IPC commands, permission system, and cross-platform development.',
    installCommand: 'npx @aidd.md/cli install knowledge tauri',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'docker-tkb',
    name: 'Docker Knowledge',
    description: 'Docker — Dockerfile best practices, multi-stage builds, compose, networking',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/infrastructure/containers/docker.md',
    contentType: 'knowledge',
    tags: ['docker', 'containers', 'multi-stage', 'compose', 'networking'],
    installCount: 1300,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-01-18',
    markdownContent: '# Docker Knowledge\n\nDockerfile best practices, multi-stage builds, compose patterns, and networking.',
    installCommand: 'npx @aidd.md/cli install knowledge docker',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'turborepo-tkb',
    name: 'Turborepo Knowledge',
    description: 'Turborepo 2 — Task pipelines, caching, filtering, remote cache, boundaries',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/tooling/monorepos/turborepo.md',
    contentType: 'knowledge',
    tags: ['turborepo', 'monorepo', 'caching', 'pipelines', 'pnpm'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Turborepo 2 Knowledge\n\nTask pipelines, intelligent caching, workspace filtering, and remote cache setup.',
    installCommand: 'npx @aidd.md/cli install knowledge turborepo',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'zod-tkb',
    name: 'Zod Knowledge',
    description: 'Zod 4 — Schema validation, type inference, transforms, refinements',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/tooling/validation/zod.md',
    contentType: 'knowledge',
    tags: ['zod', 'validation', 'schema', 'type-inference', 'typescript'],
    installCount: 1500,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-25',
    markdownContent: '# Zod 4 Knowledge\n\nSchema validation, type inference, transforms, refinements, and API boundary patterns.',
    installCommand: 'npx @aidd.md/cli install knowledge zod',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'hono-tkb',
    name: 'Hono Knowledge',
    description: 'Hono — Ultrafast web framework for edge, Cloudflare Workers, Deno, Node.js',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/backend/frameworks/hono.md',
    contentType: 'knowledge',
    tags: ['hono', 'edge', 'cloudflare-workers', 'web-framework'],
    installCount: 900,
    trending: true,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-01-28',
    markdownContent: '# Hono Knowledge\n\nUltrafast web framework for edge computing with Cloudflare Workers, Deno, and Node.js.',
    installCommand: 'npx @aidd.md/cli install knowledge hono',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'expo-tkb',
    name: 'Expo Knowledge',
    description: 'Expo 54 — Expo Router, EAS Build, Config Plugins, native modules',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/meta-frameworks/expo.md',
    contentType: 'knowledge',
    tags: ['expo', 'react-native', 'mobile', 'eas', 'router'],
    installCount: 1000,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-22',
    markdownContent: '# Expo 54 Knowledge\n\nExpo Router, EAS Build workflows, Config Plugins, and native module integration.',
    installCommand: 'npx @aidd.md/cli install knowledge expo',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'postgresql-tkb',
    name: 'PostgreSQL Knowledge',
    description: 'PostgreSQL — Indexing, JSON/JSONB, CTEs, partitioning, RLS, full-text search',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/data/databases/postgresql.md',
    contentType: 'knowledge',
    tags: ['postgresql', 'sql', 'indexing', 'jsonb', 'rls'],
    installCount: 1200,
    trending: false,
    official: true,
    createdAt: '2025-07-15',
    updatedAt: '2026-01-20',
    markdownContent: '# PostgreSQL Knowledge\n\nAdvanced indexing, JSON/JSONB, CTEs, table partitioning, and Row-Level Security.',
    installCommand: 'npx @aidd.md/cli install knowledge postgresql',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'vite-tkb',
    name: 'Vite Knowledge',
    description: 'Vite 7 — Config, plugins, HMR, build optimization, library mode',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/tooling/build/vite.md',
    contentType: 'knowledge',
    tags: ['vite', 'build', 'hmr', 'plugins', 'bundling'],
    installCount: 1100,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-01-18',
    markdownContent: '# Vite 7 Knowledge\n\nConfiguration, plugin system, HMR, build optimization, and library mode.',
    installCommand: 'npx @aidd.md/cli install knowledge vite',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'heroui-tkb',
    name: 'HeroUI Knowledge',
    description: 'HeroUI v3 — React Aria compound components, Tailwind v4, theme customization',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/frontend/ui-libraries/heroui.md',
    contentType: 'knowledge',
    tags: ['heroui', 'ui-library', 'react-aria', 'tailwind', 'components'],
    installCount: 800,
    trending: false,
    official: true,
    createdAt: '2025-09-01',
    updatedAt: '2026-01-28',
    markdownContent: '# HeroUI v3 Knowledge\n\nReact Aria compound components, Tailwind v4 integration, and theme customization.',
    installCommand: 'npx @aidd.md/cli install knowledge heroui',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'ddd-tkb',
    name: 'Domain-Driven Design Knowledge',
    description: 'DDD — Aggregates, entities, value objects, bounded contexts, domain events',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/knowledge/patterns/domain-driven-design.md',
    contentType: 'knowledge',
    tags: ['ddd', 'aggregates', 'entities', 'bounded-contexts', 'domain-events'],
    installCount: 950,
    trending: false,
    official: true,
    createdAt: '2025-08-15',
    updatedAt: '2026-01-20',
    markdownContent: '# Domain-Driven Design Knowledge\n\nAggregates, entities, value objects, bounded contexts, and domain event patterns.',
    installCommand: 'npx @aidd.md/cli install knowledge ddd',
    compatibility: ['claude-code', 'cursor'],
  },

  // ── Spec (6) ──────────────────────────────────────────────────
  {
    type: 'content',
    slug: 'aidd-lifecycle-spec',
    name: 'AIDD Lifecycle',
    description: 'AI-Driven Development — 6-phase lifecycle from UNDERSTAND to SHIP',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/specs/aidd-lifecycle.md',
    contentType: 'spec',
    tags: ['aidd', 'lifecycle', 'spec-driven', 'phases', 'methodology'],
    installCount: 2800,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# AIDD Lifecycle\n\nAI-Driven Development: 6-phase lifecycle where every feature flows through specification before implementation.',
    installCommand: 'npx @aidd.md/cli install spec aidd-lifecycle',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'bluf-6-spec',
    name: 'BLUF-6 Protocol',
    description: 'Structured communication — six-part framework prioritizing conclusions and trade-offs',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/specs/bluf-6.md',
    contentType: 'spec',
    tags: ['bluf', 'communication', 'protocol', 'structured-output'],
    installCount: 2200,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-28',
    markdownContent: '# BLUF-6 Protocol\n\nSix-part communication framework: Bottom Line → Analysis → Trade-offs → Optimal Path → Black Swans → Unknowns.',
    installCommand: 'npx @aidd.md/cli install spec bluf-6',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'heuristics-spec',
    name: 'Decision Heuristics',
    description: '10 operating principles — cognitive tools for consistent decision-making under uncertainty',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/specs/heuristics.md',
    contentType: 'spec',
    tags: ['heuristics', 'decision-making', 'principles', 'cognitive-tools'],
    installCount: 1900,
    trending: false,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-01-25',
    markdownContent: '# Decision Heuristics\n\n10 operating principles for consistent, high-quality decision-making under uncertainty.',
    installCommand: 'npx @aidd.md/cli install spec heuristics',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'memory-layer-spec',
    name: 'Memory Layer',
    description: 'Persistent structured memory — decisions, mistakes, conventions across sessions',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/specs/memory-layer.md',
    contentType: 'spec',
    tags: ['memory', 'persistence', 'sessions', 'decisions', 'conventions'],
    installCount: 2100,
    trending: true,
    official: true,
    createdAt: '2025-06-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Memory Layer\n\nPersistent, structured memory that accumulates project decisions, mistakes, and conventions across sessions.',
    installCommand: 'npx @aidd.md/cli install spec memory-layer',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'version-protocol-spec',
    name: 'Version Verification Protocol',
    description: '4-step stack validation — detect, verify, and validate project dependencies',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/specs/version-protocol.md',
    contentType: 'spec',
    tags: ['version', 'verification', 'dependencies', 'stack-validation'],
    installCount: 1600,
    trending: false,
    official: true,
    createdAt: '2025-07-01',
    updatedAt: '2026-01-20',
    markdownContent: '# Version Verification Protocol\n\n4-step process: Detect Project Stack → Load Context → Verify Docs → Anti-Legacy Filter.',
    installCommand: 'npx @aidd.md/cli install spec version-protocol',
    compatibility: ['claude-code', 'cursor'],
  },
  {
    type: 'content',
    slug: 'supported-agents-spec',
    name: 'Supported Agents Registry',
    description: 'AI coding agents & editors — configuration paths, skill loading, detection methods',
    author: 'aidd.md',
    githubUrl: 'https://github.com/DerianAndre/aidd.md/tree/main/content/specs/supported-agents.md',
    contentType: 'spec',
    tags: ['agents', 'editors', 'configuration', 'detection', 'compatibility'],
    installCount: 1400,
    trending: false,
    official: true,
    createdAt: '2025-08-01',
    updatedAt: '2026-02-01',
    markdownContent: '# Supported Agents Registry\n\nRegistry of AI coding agents/editors with configuration paths, skill loading, and detection methods.',
    installCommand: 'npx @aidd.md/cli install spec supported-agents',
    compatibility: ['claude-code', 'cursor'],
  },
];
